AsmFile with small shell at end, all alpha keys go to shell

movement                   commands         tools (alt-t)
--------                   --------         -----
up,down,pgup,pgdn          fileset -f1      reference alt-i
switch panes - tab         find    -f2      colors    alt-c
enter dir - right arrow    view    -f3      disasm    alt-u
prev. dir - left arrow     edit    -f4      src gen   alt-a
                           copy    -f5      timer     alt-e
shell ctrl                 move    -f6      plan      alt-p
----------                 mkdir   -f7      key_echo  alt-k
toggle shell - ctrl-o      delete  -f8      project   alt-j
insert path - %            unpak   -f9      make      alt-m
feed shell - alpha char    tar.gz  -f10     debug     alt-d
                           compare -f11
bookmarks                  print   -f12
---------                  exit    -alt-q
select mark - alt-1 +      enter  (operate on selection)
set bookmark - shift-f1 +
                           *** enter key to leave help ***                             