#!/bin/bash
./asmmenu $0
echo "button returned code "$?
exit
#menu definition follows
buttonsize: 2,20
header: "    button list"
header: " select using mouse"
header: " or arrow keys then"
header: " <enter>"
header: ""
clear:
	#1 row 1 column 1
	returns 11

	#2 row 2 column 1
	returns 21

	#3 row 3 column 1
	returns 31

	click me to exit
	returns 41
