#!/bin/bash
./asmmenu $0
echo "button returned code "$?
exit
#menu definition follows
buttonsize: 1,26
header: "Warning: illegal operaton"
header: "Or maybe CPU failure"
header: "Programmer bug? No way!"
header: ""
clear:
	   press ESC to continue
