FileSet help

movement                                                 
--------                                          
up,down - select fields  (enter activates)                 
right,left - inside string entry, moves cursor             
right,left - outside string entry, selects fields          
tab,shift tab - selects fields                             
                                                           
selection                                                  
---------                                                  
enter - activates selected field                           
mouse click - activates field                              
esc - exits FileSet or entry of hard/symlinks                                                
                                                           
Mouse usage is not available in Console.
             
                                       
                      
                           *** enter key to leave help ***                             